version: '2.2'

services:

  interview-localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4576:4566"            # LocalStack Gateway
    environment:
      - DEFAULT_REGION=ap-southeast-1
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

